#!/bin/tcsh

lynx -width=999 -dump -hiddenlinks=ignore -image_links=no -minimal -nobold -nolist -pseudo_inlines -force_html http://www.hrwiki.org/wiki/A_Jorb_Well_Done \
  | /usr/bin/perl -pe 's/[^[:ascii:]]/+/g'\
  | tr '\-\t <>&".?,()/\\+:\!{}' '\n' \
  | tr '[A-Z]' '[a-z]' \
  | grep ^j \
  | grep b$ \
  | sort -bfd \
  | uniq -c \
  | sort -nr
