#!/usr/bin/python3
import datetime
import sys
import subprocess
import os


def countdown(date_str):
    date_format = "%Y-%m-%d"
    target_date = datetime.datetime.strptime(date_str, date_format)
    current_date = datetime.datetime.now()

    delta = target_date - current_date
    days = delta.days + 1  # Include today in the count

    if days < 0:
        print(f"{abs(days)} days since {date_str}")
    else:
        print(f"{days} days until {date_str}")


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: countdown.py <date> or countdown.py -e")
        sys.exit(1)

    arg = sys.argv[1]

    if arg == "-e":
        countdowns_file = os.path.expanduser("~/gd/local/seiton/aux/countdowns.sh")
        subprocess.run([os.environ.get("EDITOR", "vim"), countdowns_file])
    else:
        countdown(arg)
