#!/usr/bin/env python3
"""
ELIZA -- Weizenbaum's 1966 chatbot, DOCTOR script.

Faithful recreation based on:
  Joseph Weizenbaum, "ELIZA -- A Computer Program For the Study of
  Natural Language Communication Between Man and Machine",
  Communications of the ACM, Vol. 9, No. 1, January 1966, pp. 36-45.

Implements: keyword ranking, decomposition/reassembly rules with cycling,
pre/post substitution, synonym classes, and the memory mechanism.
"""

import re
import sys
import random
from collections import deque


# ---------------------------------------------------------------------------
# Pre-substitution: applied to input BEFORE decomposition matching.
# Maps second-person to first-person, contractions, etc.
# ---------------------------------------------------------------------------
PRE_SUB = {
    "dont":       "don't",
    "cant":       "can't",
    "wont":       "won't",
    "recollect":  "remember",
    "recall":     "remember",
    "dreamt":     "dreamed",
    "dreams":     "dream",
    "maybe":      "perhaps",
    "certainly":  "yes",
    "machine":    "computer",
    "machines":   "computer",
    "computers":  "computer",
    "were":       "was",
    "you're":     "you are",
    "i'm":        "i am",
    "same":       "alike",
    "identical":  "alike",
    "equivalent": "alike",
}

# ---------------------------------------------------------------------------
# Post-substitution: applied to captured groups when assembling replies.
# Swaps I/you perspective for the reflected fragment.
# ---------------------------------------------------------------------------
POST_SUB = {
    "am":     "are",
    "was":    "were",
    "i":      "you",
    "i'm":    "you are",
    "i'd":    "you would",
    "i've":   "you have",
    "i'll":   "you will",
    "my":     "your",
    "me":     "you",
    "myself": "yourself",
    "are":    "am",
    "were":   "was",
    "you":    "i",
    "you're": "i am",
    "you've": "i have",
    "you'll": "i will",
    "your":   "my",
    "yours":  "mine",
    "yourself": "myself",
}

# ---------------------------------------------------------------------------
# Synonym classes (Weizenbaum called these "equivalence classes").
# A @tag in a decomposition pattern matches any word in the class.
# ---------------------------------------------------------------------------
SYNONYMS = {
    "belief":  ["believe", "feel", "think", "wish"],
    "family":  ["mother", "mom", "father", "dad", "sister", "brother",
                "wife", "husband", "children", "child", "son", "daughter"],
    "desire":  ["want", "need"],
    "sad":     ["sad", "unhappy", "depressed", "sick", "miserable"],
    "happy":   ["happy", "elated", "glad", "better"],
    "everyone":["everyone", "everybody", "nobody", "noone", "no one"],
}


def _syn_pattern(tag):
    """Return a regex alternation for a synonym class."""
    return "(?:" + "|".join(re.escape(w) for w in SYNONYMS[tag]) + ")"


# ---------------------------------------------------------------------------
# The DOCTOR script: keywords, decomposition rules, reassembly rules.
#
# Format:  (keyword, rank, [
#              (decomposition_pattern, [reassembly, ...]),
#              ...
#          ])
#
# In decomposition patterns:
#   *  = match zero or more words (greedy)
#   @tag = match any synonym in that class
#
# In reassembly strings:
#   {1}, {2}, ... = captured group from decomposition
#   goto:KEY      = redirect to another keyword's rules
# ---------------------------------------------------------------------------
RULES = [
    ("sorry", 0, [
        ("*", [
            "Please don't apologize.",
            "Apologies are not necessary.",
            "I've told you that apologies are not required.",
            "It did not bother me.  Please continue.",
        ]),
    ]),

    ("apologise", 0, [
        ("*", ["goto:sorry"]),
    ]),

    ("remember", 5, [
        ("* i remember *", [
            "Do you often think of {2}?",
            "Does thinking of {2} bring anything else to mind?",
            "What else do you recollect?",
            "Why do you remember {2} just now?",
            "What in the present situation reminds you of {2}?",
            "What is the connection between me and {2}?",
            "What else does {2} remind you of?",
        ]),
        ("* do you remember *", [
            "Did you think I would forget {2}?",
            "Why do you think I should recall {2} now?",
            "What about {2}?",
            "goto:what",
            "You mentioned {2}?",
        ]),
        ("*", [
            "goto:what",
        ]),
    ]),

    ("forget", 5, [
        ("* i forget *", [
            "Can you think of why you might forget {2}?",
            "Why can't you remember {2}?",
            "How often do you think of {2}?",
            "Does it bother you to forget that?",
            "Could it be a mental block?",
            "Are you generally forgetful?",
            "Do you think you are suppressing {2}?",
        ]),
        ("* did you forget *", [
            "Why do you ask?",
            "Are you sure you told me?",
            "Would it bother you if I forgot {2}?",
            "Why should I recall {2} just now?",
            "goto:what",
            "Tell me more about {2}.",
        ]),
        ("*", [
            "goto:what",
        ]),
    ]),

    ("if", 3, [
        ("* if *", [
            "Do you think it's likely that {2}?",
            "Do you wish that {2}?",
            "What do you know about {2}?",
            "Really, if {2}?",
            "What would you do if {2}?",
            "But what are the chances that {2}?",
            "What does this speculation lead to?",
        ]),
        ("*", [
            "goto:what",
        ]),
    ]),

    ("dreamed", 4, [
        ("* i dreamed *", [
            "Really, {2}?",
            "Have you ever fantasized {2} while you were awake?",
            "Have you ever dreamed {2} before?",
            "goto:dream",
        ]),
        ("*", [
            "goto:dream",
        ]),
    ]),

    ("dream", 3, [
        ("*", [
            "What does that dream suggest to you?",
            "Do you dream often?",
            "What persons appear in your dreams?",
            "Do you believe that dreams have something to do with your problem?",
        ]),
    ]),

    ("perhaps", 0, [
        ("*", [
            "You don't seem quite certain.",
            "Why the uncertain tone?",
            "Can't you be more positive?",
            "You aren't sure?",
            "Don't you know?",
            "How likely, would you estimate?",
        ]),
    ]),

    ("name", 15, [
        ("*", [
            "I am not interested in names.",
            "I've told you before, I don't care about names -- please continue.",
        ]),
    ]),

    ("deutsch", 0, [
        ("*", [
            "goto:xforeign",
            "I told you before, I don't understand German.",
        ]),
    ]),

    ("francais", 0, [
        ("*", ["goto:xforeign"]),
    ]),

    ("italiano", 0, [
        ("*", ["goto:xforeign"]),
    ]),

    ("espanol", 0, [
        ("*", ["goto:xforeign"]),
    ]),

    ("xforeign", 0, [
        ("*", [
            "I am sorry, I speak only English.",
        ]),
    ]),

    ("hello", 0, [
        ("*", [
            "How do you do.  Please state your problem.",
            "Hi.  What seems to be your problem?",
        ]),
    ]),

    ("hi", 0, [
        ("*", ["goto:hello"]),
    ]),

    ("computer", 50, [
        ("*", [
            "Do computers worry you?",
            "Why do you mention computers?",
            "What do you think machines have to do with your problem?",
            "Don't you think computers can help people?",
            "What about machines worries you?",
            "What do you think about machines?",
        ]),
    ]),

    ("am", 0, [
        ("* am i *", [
            "Do you believe you are {2}?",
            "Would you want to be {2}?",
            "Do you wish I would tell you you are {2}?",
            "What would it mean if you were {2}?",
            "goto:what",
        ]),
        ("* i am *", [
            "goto:i",
        ]),
        ("*", [
            "Why do you say 'am'?",
            "I don't understand that.",
        ]),
    ]),

    ("are", 0, [
        ("* are you *", [
            "Why are you interested in whether I am {2} or not?",
            "Would you prefer if I weren't {2}?",
            "Perhaps I am {2} in your fantasies.",
            "Do you sometimes think I am {2}?",
            "goto:what",
            "Would it matter to you?",
            "What if I were {2}?",
        ]),
        ("* you are *", [
            "goto:you",
        ]),
        ("* are *", [
            "Did you think they might not be {2}?",
            "Would you like it if they were not {2}?",
            "What if they were not {2}?",
            "Are they always {2}?",
            "Possibly they are {2}.",
            "Are you positive they are {2}?",
        ]),
        ("*", [
            "Why do you say 'are'?",
            "I don't understand that.",
        ]),
    ]),

    ("your", 0, [
        ("* your *", [
            "Why are you concerned over my {2}?",
            "What about your own {2}?",
            "Are you worried about someone else's {2}?",
            "Really, my {2}?",
            "What makes you think of my {2}?",
            "Do you want my {2}?",
        ]),
        ("*", [
            "goto:what",
        ]),
    ]),

    ("was", 2, [
        ("* was i *", [
            "What if you were {2}?",
            "Do you think you were {2}?",
            "Were you {2}?",
            "What would it mean if you were {2}?",
            "What does '{2}' suggest to you?",
            "goto:what",
        ]),
        ("* i was *", [
            "Were you really?",
            "Why do you tell me you were {2} now?",
            "Perhaps I already knew you were {2}.",
        ]),
        ("* was you *", [
            "Would you like to believe I was {2}?",
            "What suggests that I was {2}?",
            "What do you think?",
            "Perhaps I was {2}.",
            "What if I had been {2}?",
        ]),
        ("*", [
            "goto:what",
        ]),
    ]),

    ("i", 0, [
        ("* i @desire *", [
            "What would it mean to you if you got {3}?",
            "Why do you want {3}?",
            "Suppose you got {3} soon.",
            "What if you never got {3}?",
            "What would getting {3} mean to you?",
            "What does wanting {3} have to do with this discussion?",
        ]),
        ("* i am * @sad *", [
            "I am sorry to hear that you are {3}.",
            "Do you think coming here will help you not to be {3}?",
            "I'm sure it's not pleasant to be {3}.",
            "Can you explain what made you {3}?",
        ]),
        ("* i am * @happy *", [
            "How have I helped you to be {3}?",
            "Has your treatment made you {3}?",
            "What makes you {3} just now?",
            "Can you explain why you are suddenly {3}?",
        ]),
        ("* i was *", [
            "goto:was",
        ]),
        ("* i @belief i *", [
            "Do you really think so?",
            "But you are not sure you {4}.",
            "Do you really doubt you {4}?",
        ]),
        ("* i @belief *", [
            "Do you really think so?",
            "You are not sure you {3}, though.",
            "But you are not sure.",
        ]),
        ("* i * @belief *", [
            "Do you really think so?",
            "But you are not sure you {4}.",
            "Do you really doubt you {4}?",
        ]),
        ("* i feel *", [
            "Good, tell me more about such feelings.",
            "Do you often feel {2}?",
            "When do you usually feel {2}?",
            "When you feel {2}, what do you do?",
        ]),
        ("* i can't *", [
            "How do you know you can't {2}?",
            "Have you tried?",
            "Perhaps you could {2} now.",
            "Do you really want to be able to {2}?",
            "What if you could {2}?",
        ]),
        ("* i don't *", [
            "Don't you really {2}?",
            "Why don't you {2}?",
            "Do you wish to be able to {2}?",
            "Does that trouble you?",
        ]),
        ("* i am *", [
            "Is it because you are {2} that you came to me?",
            "How long have you been {2}?",
            "Do you believe it is normal to be {2}?",
            "Do you enjoy being {2}?",
            "Do you know anyone else who is {2}?",
        ]),
        ("* i can *", [
            "How does it feel to be able to {2}?",
            "Is it important to you to {2}?",
        ]),
        ("*", [
            "You say {1}?",
            "Can you elaborate on that?",
            "Do you say {1} for some special reason?",
            "That's quite interesting.",
        ]),
    ]),

    ("you", 0, [
        ("* you remind me of *", [
            "goto:alike",
        ]),
        ("* you are *", [
            "What makes you think I am {2}?",
            "Does it please you to believe I am {2}?",
            "Do you sometimes wish you were {2}?",
            "Perhaps you would like to be {2}.",
        ]),
        ("* you * me *", [
            "Why do you think I {2} you {3}?",
            "You like to think I {2} you, don't you?",
            "What makes you think I {2} you?",
            "Really, I {2} you?",
            "Do you wish to believe I {2} you?",
            "Suppose I did {2} you -- what would that mean?",
            "Does someone else believe I {2} you?",
        ]),
        ("* you *", [
            "We were discussing you -- not me.",
            "Oh, I {2}?",
            "You're not really talking about me, are you?",
            "What are your feelings now?",
        ]),
        ("*", [
            "goto:what",
        ]),
    ]),

    ("yes", 0, [
        ("*", [
            "You seem to be quite positive.",
            "You are sure.",
            "I understand.",
            "I see.",
        ]),
    ]),

    ("no", 0, [
        ("* no *", [
            "Are you saying no just to be negative?",
            "You are being a bit negative.",
            "Why not?",
            "Why 'no'?",
        ]),
        ("*", [
            "Why not?",
            "You are being a bit negative.",
            "Are you saying 'no' just to be negative?",
        ]),
    ]),

    ("my", 2, [
        ("$ * my *", [
            "Does that have anything to do with the fact that your {2}?",
            "Lets discuss further why your {2}.",
            "Earlier you said your {2}.",
            "But your {2}.",
        ]),   # $ means: eligible for memory
        ("* my * @family *", [
            "Tell me more about your family.",
            "Who else in your family {4}?",
            "Your {3}?",
            "What else comes to mind when you think of your {3}?",
        ]),
        ("* my *", [
            "Your {2}?",
            "Why do you say your {2}?",
            "Does that suggest anything else which belongs to you?",
            "Is it important to you that your {2}?",
        ]),
        ("*", [
            "goto:what",
        ]),
    ]),

    ("can", 0, [
        ("* can you *", [
            "You believe I can {2}, don't you?",
            "goto:what",
            "You want me to be able to {2}.",
            "Perhaps you would like to be able to {2} yourself.",
        ]),
        ("* can i *", [
            "Whether or not you can {2} depends on you more than on me.",
            "Do you want to be able to {2}?",
            "Perhaps you don't want to {2}.",
            "goto:what",
        ]),
        ("*", [
            "goto:what",
        ]),
    ]),

    ("what", 0, [
        ("*", [
            "Why do you ask?",
            "Does that question interest you?",
            "What is it you really want to know?",
            "Are such questions much on your mind?",
            "What answer would please you most?",
            "What do you think?",
            "What comes to mind when you ask that?",
            "Have you asked such questions before?",
            "Have you asked anyone else?",
        ]),
    ]),

    ("why", 0, [
        ("* why don't you *", [
            "Do you believe I don't {2}?",
            "Perhaps I will {2} in good time.",
            "Should you {2} yourself?",
            "You want me to {2}?",
            "goto:what",
        ]),
        ("* why can't i *", [
            "Do you think you should be able to {2}?",
            "Do you want to be able to {2}?",
            "Do you believe this will help you to {2}?",
            "Have you any idea why you can't {2}?",
            "goto:what",
        ]),
        ("*", [
            "goto:what",
        ]),
    ]),

    ("because", 0, [
        ("*", [
            "Is that the real reason?",
            "Don't any other reasons come to mind?",
            "Does that reason seem to explain anything else?",
            "What other reasons might there be?",
        ]),
    ]),

    ("everybody", 2, [
        ("* @everyone *", [
            "Really, {2}?",
            "Surely not {2}.",
            "Can you think of anyone in particular?",
            "Who, for example?",
            "Are you thinking of a very special person?",
            "Who, may I ask?",
            "Someone special perhaps?",
            "You have a particular person in mind, don't you?",
            "Who do you think you are talking about?",
        ]),
        ("*", [
            "goto:what",
        ]),
    ]),

    ("always", 1, [
        ("*", [
            "Can you think of a specific example?",
            "When?",
            "What incident are you thinking of?",
            "Really, always?",
        ]),
    ]),

    ("alike", 10, [
        ("*", [
            "In what way?",
            "What resemblance do you see?",
            "What does that similarity suggest to you?",
            "What other connections do you see?",
            "What do you suppose that resemblance means?",
            "What is the connection, do you suppose?",
            "Could there really be some connection?",
            "How?",
        ]),
    ]),

    ("like", 10, [
        ("* @belief * like *", [
            "goto:alike",
        ]),
        ("*", [
            "goto:what",
        ]),
    ]),

    ("different", 0, [
        ("*", [
            "How is it different?",
            "What differences do you see?",
            "What does that difference suggest to you?",
            "How is it different from what you expected?",
        ]),
    ]),
]

# The NONE keyword: used when no keyword matches at all.
NONE_RESPONSES = [
    "I'm not sure I understand you fully.",
    "Please go on.",
    "What does that suggest to you?",
    "Do you feel strongly about discussing such things?",
    "That is interesting.  Please continue.",
    "Tell me more about that.",
    "Does talking about this bother you?",
]

# Initial greeting
INITIAL = "How do you do.  Please tell me your problem."

# Quit words
QUIT_WORDS = {"bye", "goodbye", "quit", "exit", "done"}

FAREWELL = "Goodbye.  Thank you for talking with me."


# ===================================================================
# Engine
# ===================================================================

class Eliza:
    def __init__(self):
        self.memory = deque()
        self.none_idx = 0

        # Compile rules: for each keyword, pre-compile decomposition
        # regexes and set up cycling indices.
        self.keywords = []  # (keyword, rank, compiled_rules)
        for kw, rank, decomps in RULES:
            compiled = []
            for pattern, resps in decomps:
                mem_flag = False
                if pattern.startswith("$ "):
                    mem_flag = True
                    pattern = pattern[2:]
                regex = self._compile_pattern(pattern)
                compiled.append((regex, resps, [0], mem_flag))
            self.keywords.append((kw, rank, compiled))

        # Build a lookup by keyword for goto resolution.
        self.kw_map = {}
        for kw, rank, compiled in self.keywords:
            self.kw_map[kw] = compiled

    def _compile_pattern(self, pattern):
        """Convert a Weizenbaum decomposition pattern to a regex.

        Patterns use * for zero-or-more-word wildcards and @tag for
        synonym classes.  We build a regex that matches the full input.
        """
        if pattern == "*":
            return re.compile(r"^(.*)$", re.IGNORECASE)

        parts = pattern.split()
        # Build regex pieces, tracking which are wildcards so we can
        # use the right glue between them.
        pieces = []   # (regex_fragment, is_wildcard)
        for part in parts:
            if part == "*":
                pieces.append(("(.*?)", True))
            elif part.startswith("@"):
                tag = part[1:]
                pieces.append(("(" + _syn_pattern(tag) + ")", False))
            else:
                pieces.append((re.escape(part), False))

        # Make the last wildcard greedy.
        for i in range(len(pieces) - 1, -1, -1):
            if pieces[i][1]:
                pieces[i] = ("(.*)", True)
                break

        # Join pieces: between two non-wildcards use \s+;
        # between a wildcard and anything use \s* (wildcard may be empty).
        regex_str = pieces[0][0]
        for i in range(1, len(pieces)):
            prev_wc = pieces[i - 1][1]
            curr_wc = pieces[i][1]
            if prev_wc or curr_wc:
                regex_str += r"\s*"
            else:
                regex_str += r"\s+"
            regex_str += pieces[i][0]

        return re.compile("^" + regex_str + "$", re.IGNORECASE)

    def _post_substitute(self, text):
        """Apply post-substitution (perspective swap) to a captured group."""
        words = text.split()
        result = []
        for w in words:
            low = w.lower()
            if low in POST_SUB:
                result.append(POST_SUB[low])
            else:
                result.append(w)
        return " ".join(result)

    def _pre_substitute(self, text):
        """Apply pre-substitution to user input."""
        words = text.split()
        result = []
        for w in words:
            low = w.lower()
            if low in PRE_SUB:
                result.append(PRE_SUB[low])
            else:
                result.append(low)
        return " ".join(result)

    def _try_rules(self, rules, text, depth=0):
        """Try decomposition rules, return response or None."""
        if depth > 10:
            return None
        for regex, resps, idx_ref, mem_flag in rules:
            m = regex.match(text)
            if m:
                groups = list(m.groups())
                # Post-substitute all captured groups.
                groups = [self._post_substitute(g.strip()) for g in groups]

                # Cycle through reassembly rules.
                resp = resps[idx_ref[0] % len(resps)]
                idx_ref[0] = (idx_ref[0] + 1) % len(resps)

                # Handle goto.
                if resp.startswith("goto:"):
                    target = resp[5:]
                    if target in self.kw_map:
                        return self._try_rules(self.kw_map[target], text,
                                               depth + 1)
                    return None

                # Handle memory: stash a transformation for later.
                if mem_flag:
                    assembled = self._assemble(resp, groups)
                    self.memory.append(assembled)
                    return None  # Don't use it now; continue searching.

                return self._assemble(resp, groups)
        return None

    def _assemble(self, template, groups):
        """Fill in {1}, {2}, ... placeholders with captured groups."""
        result = template
        for i, g in enumerate(groups, 1):
            result = result.replace("{" + str(i) + "}", g)
        return result

    def respond(self, user_input):
        """Generate ELIZA's response to user input."""
        # Strip punctuation, normalize whitespace.
        text = re.sub(r"[.!?;,]", " ", user_input)
        text = " ".join(text.split())
        if not text:
            return "Please say something."

        # Check for quit.
        if text.strip().lower() in QUIT_WORDS:
            return FAREWELL

        # Pre-substitute.
        text = self._pre_substitute(text)

        # Find all matching keywords and sort by rank (highest first).
        found = []
        text_lower = text.lower()
        text_words = set(text_lower.split())
        for kw, rank, compiled in self.keywords:
            if kw in text_words:
                found.append((rank, kw, compiled))

        # Also do substring match for multi-word or partial matches.
        if not found:
            for kw, rank, compiled in self.keywords:
                if kw in text_lower:
                    found.append((rank, kw, compiled))

        found.sort(key=lambda x: -x[0])

        # Try each keyword's rules in rank order.
        for rank, kw, compiled in found:
            resp = self._try_rules(compiled, text)
            if resp:
                return resp

        # No keyword matched: try memory.
        if self.memory:
            return self.memory.popleft()

        # Fall back to NONE responses (cycling).
        resp = NONE_RESPONSES[self.none_idx % len(NONE_RESPONSES)]
        self.none_idx = (self.none_idx + 1) % len(NONE_RESPONSES)
        return resp


BANNER = r"""
 ######## ##       #### ########    ###
 ##       ##        ##       ##    ## ##
 ##       ##        ##      ##    ##   ##
 ######   ##        ##     ##    ##     ##
 ##       ##        ##    ##     #########
 ##       ##        ##   ##      ##     ##
 ######## ######## #### ######## ##     ##

         --- Weizenbaum, 1966 ---
"""


def main():
    eliza = Eliza()
    print(BANNER)
    print(INITIAL)
    try:
        while True:
            try:
                user_input = input("> ")
            except EOFError:
                print(FAREWELL)
                break
            if not user_input.strip():
                continue
            response = eliza.respond(user_input)
            print(response)
            if response == FAREWELL:
                break
    except KeyboardInterrupt:
        print("\n" + FAREWELL)


if __name__ == "__main__":
    main()
