#!/bin/bash
# List repositories I've pushed to recently - using repo list API

# Default GitHub user
USER="chrishwiggins"
LIMIT="--limit 20"

# Parse arguments
while [ $# -gt 0 ]; do
    case "$1" in
        -u|--user)
            USER="$2"
            shift 2
            ;;
        0)
            LIMIT=""
            shift
            ;;
        [0-9]*)
            LIMIT="--limit $1"
            shift
            ;;
        *)
            USER="$1"
            shift
            ;;
    esac
done

echo "Recent GitHub repositories for $USER:"
echo

# Get repositories sorted by push date
gh repo list "$USER" $LIMIT --json name,pushedAt |
  jq -r --arg user "$USER" 'sort_by(.pushedAt) | reverse | .[] | "\(.name) (\(.pushedAt | fromdateiso8601 | strftime("%Y-%m-%d"))) - https://github.com/\($user)/\(.name)"'
