#!/bin/bash

# Prepare temporary files
tmp_old="/tmp/old_$$"
tmp_new="/tmp/new_$$"
tmp_mvs="/tmp/mvs.sh"

# Capture the list of filenames to normalize
find . -type f | grep -E ' |,|-|_' > "$tmp_old"

# Normalize filenames: replace sequences of spaces, commas, dashes, and underscores with a single underscore
# Replace single quotes with underscore and brackets with hyphens
cat "$tmp_old" | sed -e 's/[, _-][, _-]*/_/g' -e "s/'/_/g" | tr '()' '-' > "$tmp_new"

# Generate move commands
paste "$tmp_old" "$tmp_new" | awk '{print "mv -f \"" $1 "\" \"" $2 "\""}' > "$tmp_mvs"

# Execute the move commands
source "$tmp_mvs"

# Clean up
rm "$tmp_old" "$tmp_new" "$tmp_mvs"
