#!/bin/csh

setenv afile $1

echo "files to send:"
echo
ls -1 *.eml  | awk '{print NR,$0}'
echo
sleep 2


setenv odir "sent/`date +%yy%mm%dd_%Hh%Mm%Ss`"
#echo $odir
mkdir -pv $odir

foreach thing (*.eml)
    echo "sending" $thing "..."
    if ($#argv > 0) then
      if ( -e $afile ) then
        cat /dev/null | mutt -H $thing -a $afile
       else
        cat /dev/null | mutt -H $thing 
      endif
    endif
    echo "... $thing done"
    mv -f $thing $odir
end
