#!/bin/csh

setenv afile $1

echo "files to send:"
echo
ls -1 *.eml  | awk '{print NR,$0}'
echo
sleep 2


setenv odir "sent/`date +%yy%mm%dd_%Hh%Mm%Ss`"
#echo $odir
mkdir -pv $odir

foreach thing (*.eml)
    if ($#argv > 0) then
      if ( -e $afile ) then
        echo "sending" $thing "with attachment file" $afile "..."
        cat /dev/null | mutt -H $thing -a $afile
      else
        echo "error: "$afile" does not exist"
      endif
      else
        echo "sending" $thing "with no attachment..."
        cat /dev/null | mutt -H $thing 
    endif
    echo "... $thing done"
    mv -f $thing $odir
end
