#!/bin/tcsh -f #-X -V
#% turns + into quotes
#% turns spaces into URL spaces (%22)
#% http://search.twitter.com/search?q=this+is+%22a+phrase%22

set str=`echo $* | sed -e 's/+/%22/g' | sed -e 's/ /+/g' `
echo $str
open 'http://twitter.com/search?f=realtime&q='$str'&src=typd'
