#!/bin/tcsh -f #-X -V
#% turns + into quotes
#% turns spaces into URL spaces (%22)
#% http://search.twitter.com/search?q=this+is+%22a+phrase%22

set str=`echo $* | sed -e 's/+/%22/g' | sed -e 's/ /+/g' `
echo $str
# brave breaks
#open -a safari 'http://twitter.com/search?f=realtime&q='$str'&src=typd' 
# back to brave 20211022
open -a ~/bin/brave 'http://twitter.com/search?f=realtime&q='$str'&src=typd'
