#!/bin/tcsh
# Set window to blue with optional title
osascript -e 'tell application "Terminal" to set background color of window 1 to {10000, 10000, 30000}'
if ($#argv > 0) printf "\033]0;%s\007" "$*"
