#!/bin/tcsh -f #-X -V
#% open your browser in a search
#% eliminates spaces
#% turns / (for dates) into url-formatted /
#
# ex https://docs.google.com/#search/projects

set str=`echo $* | sed -e 's/\ /+/g' -e 's/\//%2F/g'` 
# echo $str
#
# changed 2014-12-19
# open 'https://drive.google.com/?authuser=0#search/'$str
#
open 'https://drive.google.com/drive/u/0/#search?q='$str
