#!/bin/tcsh -f #-X -V
#% wraps around ddg, turns + into quotes
#% turns spaces into URL spaces (%22)

set str=`echo $* | sed -e 's/+/%22/g' | sed -e 's/ /+/g' `
echo $str
open 'https://duckduckgo.com/?q='$str
