#!/bin/tcsh -f #-X -V
#% wraps around google, turns + into quotes
#% turns spaces into URL spaces (%22)

set str=`echo $* | sed -e 's/+/%22/g' | sed -e 's/ /+/g' `
echo $str
open 'https://www.google.com/search?tbm=bks&q='$str

# examples
# https://www.google.com/search?tbm=bks&q=word+%22a+phrase%22
