#!/bin/tcsh
# Set window to green with optional title
osascript -e 'tell application "Terminal" to set background color of window 1 to {10000, 30000, 10000}'
if ($#argv > 0) printf "\033]0;%s\007" "$*"
