#!/bin/tcsh -f #-X -V
#% wraps around google maps, turns + into quotes
#% turns spaces into URL spaces (%22)

set str=`echo $* | sed -e 's/ /%20/g'`
echo $str
# firefox no good for gmap as of 2014-06-27
# open  'http://maps.google.com/maps?um=1&tab=wl&hl=en&lr=&q='$str
open  'http://www.google.com/maps/dir/'$str

#new syntax
#https://www.google.com/maps/dir/251+mercer+street/500+w+120th+street/
# e.g., 
# wiggins{~}: map 251 mercer street/500 w 120th street 
