#!/bin/tcsh -f #-X -V
#% wraps around google maps, turns + into quotes
#% turns spaces into URL spaces (%22)

set str=`echo $* | sed -e 's/ /%20/g'`
echo $str
# firefox no good for gmap as of 2014-06-27
chrome 'http://maps.google.com/maps?um=1&tab=wl&hl=en&lr=&q='$str
