#!/bin/tcsh -f #-X -V
#% wraps around google maps, turns + into quotes
#% turns spaces into URL spaces (%22)
# make sure you include "/" in the input, separating places

set str=`echo $* | sed -e 's/ /%20/g'`
echo $str
open  'http://www.google.com/maps/dir/'$str
