#!/bin/tcsh -f #-X -V
#% wraps around google, turns + into quotes
#% turns spaces into URL spaces (%22)

if ( $#argv != 1 ) then
    open http://news.google.com/
else
    set str=`echo $* | sed -e 's/+/%22/g' | sed -e 's/ /+/g' `
    echo $str
    open 'http://www.google.com/search?hl=en&gl=us&tbm=nws&btnmeta_news_search=1&q='$str
endif
