#!/bin/tcsh -f #-X -V
#% wraps around google, turns + into quotes
#% turns spaces into URL spaces (%22)

if ( $#argv != 1 ) then
    open http://news.google.com/
else
    set str=`echo $* | sed -e 's/+/%22/g' | sed -e 's/ /+/g' `
    echo $str
    open 'http://www.google.com/search?hl=en&gl=us&tbm=nws&btnmeta_news_search=1&q='$str
endif

# ex https://www.google.com/search?hl=en&gl=us&tbm=nws&btnmeta_news_search=1&q=str+1+str2&oq=str+1+str2&aq=f&aqi=d1d-o1&aql=&gs_sm=e&gs_upl=5806l8455l0l8590l13l12l0l6l6l1l141l550l4.2l6l0
