#!/bin/tcsh
 
## Check if --help option is provided
if ("$1" == "--help") then
    tesseract --list-langs
    exit 0
endif

# Check if at least two arguments are provided
if ($#argv < 1) then
    echo "Usage: ocr input_file [options]"
    echo "e.g., ocr foo.png -l fra --oem 1"
    exit 1
endif

set input_file = $1
shift

set options = "$*"
if ($#argv < 2) then
    set options = "-l eng --oem 1"
    #echo "e.g., ocr foo.png -l fra --oem 1"
    #exit 1
endif

echo "STARTING ocr on $input_file at `date` ..."

# convert to tiff
echo "  - starting convert to tiff $input_file at `date`"
time convert -density 300 $input_file -depth 8 -strip -background white -alpha off /tmp/ocr_$$.tiff

echo "  - finished convert to tiff $input_file at `date`"

echo "  - starting tesseract at `date` with:"
echo "    + options = $options"
echo "    + input = $input_file"

echo "  - starting tesseract /tmp/ocr_$$.tiff $input_file:r $options at `date`"
echo "command:"
echo "tesseract /tmp/ocr_$$.tiff $input_file:r $options"

# most important line in the code:
time tesseract /tmp/ocr_$$.tiff $input_file:r $options

echo "  - ending tesseract /tmp/ocr_$$.tiff $input_file:r $options at `date`"

# maybe change this to mv -f after testing for a while.
mv -v -i ${input_file:r}.txt ${input_file:r}.ocr
#
# might need cleanup:
# rm -f /tmp/ocr_$$.tiff
# echo removed /tmp/ocr_$$.tiff

# [1] https://diging.atlassian.net/wiki/spaces/DCH/pages/5275668/Tutorial+Text+Extraction+and+OCR+with+Tesseract+and+ImageMagick 
# [2]
# Usage:
#    tesseract --help | --help-psm | --help-oem | --version
#    tesseract --list-langs [--tessdata-dir PATH]
#    tesseract --print-parameters [options...] [configfile...]
#    tesseract imagename|stdin outputbase|stdout [options...] [configfile...]
#  
#  OCR options:
#    --tessdata-dir PATH   Specify the location of tessdata path.
#    --user-words PATH     Specify the location of user words file.
#    --user-patterns PATH  Specify the location of user patterns file.
#    -l LANG[+LANG]        Specify language(s) used for OCR.
#    -c VAR=VALUE          Set value for config variables.
#                          Multiple -c arguments are allowed.
#    --psm NUM             Specify page segmentation mode.
#    --oem NUM             Specify OCR Engine mode.
#  NOTE: These options must occur before any configfile.
#  
#  Page segmentation modes:
#    0    Orientation and script detection (OSD) only.
#    1    Automatic page segmentation with OSD.
#    2    Automatic page segmentation, but no OSD, or OCR.
#    3    Fully automatic page segmentation, but no OSD. (Default)
#    4    Assume a single column of text of variable sizes.
#    5    Assume a single uniform block of vertically aligned text.
#    6    Assume a single uniform block of text.
#    7    Treat the image as a single text line.
#    8    Treat the image as a single word.
#    9    Treat the image as a single word in a circle.
#   10    Treat the image as a single character.
#   11    Sparse text. Find as much text as possible in no particular order.
#   12    Sparse text with OSD.
#   13    Raw line. Treat the image as a single text line,
#        bypassing hacks that are Tesseract-specific.
#  OCR Engine modes:
#    0    Original Tesseract only.
#    1    Cube only.
#    2    Tesseract + cube.
#    3    Default, based on what is available.
#  
#  Single options:
#    -h, --help            Show this help message.
#    --help-psm            Show page segmentation modes.
#    --help-oem            Show OCR Engine modes.
#    -v, --version         Show version information.
#    --list-langs          List available languages for tesseract engine.
#    --print-parameters    Print tesseract parameters to stdout.
