#!/bin/tcsh -f #-X -V
#% wraps around slideshare search, 
#%  turns + into quotes
#%  turns spaces into URL spaces (%22)

set str=`echo $* | sed -e 's/+/%22/g' | sed -e 's/ /+/g' `
echo $str
open 'http://www.slideshare.net/search/slideshow?searchfrom=header&q='


# examples
# http://www.slideshare.net/search/slideshow?searchfrom=header&q=word+%22a+phrase%22
