#!/bin/bash

# Set default profile number and URL
#PROFILE_NUMBER="Default"  # Use "Default" or specify a default profile number
PROFILE_NUMBER="1" 
URL="${2:-about:blank}"

# Check if no profile argument is provided
if [ $# -eq 0 ]; then
    # If no arguments are provided, use default profile and open about:blank or a specified default URL
    echo "No arguments provided. Opening an empty window with the default profile."
elif [ $# -eq 1 ]; then
    # If only one argument is provided, treat it as the profile number
    PROFILE_NUMBER="$1"
else
    # If both arguments are provided, use them as specified
    PROFILE_NUMBER="$1"
    URL="$2"
fi

# Use the determined profile and URL to open Chrome
/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --profile-directory="Profile $PROFILE_NUMBER" "$URL"
