#!/bin/bash
# Set window to yellow with optional title
osascript -e 'tell application "Terminal" to set background color of window 1 to {30000, 30000, 10000}'
[[ -n "$*" ]] && printf "\033]0;%s\007" "$*"
